title: 椭圆的前端之路
encoding: utf-8
baseurl: /
paginate: 5
paginate_path: "page:num"
permalink: /:year/:month/:day/:title
exclude: ["node_modules", "Gruntfile.js", "package.json", "src"]
markdown: Kramdown
