title: 椭圆的前端之路
encoding: utf-8
baseurl: "" 
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
paginate: 5
paginate_path: "page:num"

# Build settings
markdown: kramdown
