title: 椭圆的前端之路
encoding: utf-8
baseurl: /
paginate: 5
paginate_path: "page:num"
permalink: /:year/:month/:day/:title
markdown: redcarpet
redcarpet:
extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
